language: go
go:
  - "1.9"

install:
  - go get github.com/yusukemisa/goConvImgExtention

script:
  - go test -coverprofile=profile github.com/yusukemisa/goConvImgExtention/convertor

after_success:
  - bash <(curl -s https://codecov.io/bash)

